# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180606_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='meal_choice',
            field=models.CharField(default='Planned', max_length=10, verbose_name='Meal choice'),
        ),
    ]
