# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-07 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20180523_1818'),
        ('email', '0002_auto_20180606_1134'),
    ]

    operations = [
    ]
