# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-08 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180606_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_users',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_from_api',
            field=models.NullBooleanField(),
        ),
    ]
