# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-31 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180531_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_users',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_from_api',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_english_ingredients',
            field=models.BooleanField(default=True, help_text='Check to also show ingredients in English while creating\na nutritional plan. These ingredients are extracted from a list provided\nby the US Department of Agriculture. It is extremely complete,\nwith around 7000 entries,\nbut can be somewhat overwhelming and make the search difficult.', verbose_name='Also use ingredients in English'),
        ),
    ]
