# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180606_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofweek',
            name='plan_type',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
