# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-07 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180606_1134'),
        ('core', '0011_auto_20180531_1225'),
    ]

    operations = [
    ]
