# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-18 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180608_1216'),
        ('core', '0015_merge'),
    ]

    operations = [
    ]
