# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-17 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180606_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='cycle',
            field=models.CharField(choices=[('Microcycle', 'Microcycle - Up to one week'), ('Mesocycle', 'Mesocycle - Two to six weeks'), ('Macrocycle', 'Macrocycle - Up to one year'), ('None', 'None Selected')], default='None', max_length=10),
        ),
    ]
