# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-18 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_workout_cycle'),
        ('manager', '0009_merge'),
    ]

    operations = [
    ]
